FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY . .

RUN chmod +x mvnw 2>/dev/null || true

RUN ./mvnw -pl auth-service/auth-service -am clean package -DskipTests

EXPOSE 8081

CMD ["java", "-jar", "auth-service/auth-service/target/auth-service-0.0.1-SNAPSHOT.jar"]
