FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY . .

RUN mvn -pl auth-service/auth-service -am clean package -DskipTests

EXPOSE 8081

CMD ["mvn", "-f", "auth-service/auth-service/pom.xml", "spring-boot:run"]
