FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY . .

RUN mvn -pl auth-service/auth-service -am clean package -DskipTests

EXPOSE 8081

CMD ["java", "-jar", "auth-service/auth-service/target/auth-service-0.0.1-SNAPSHOT.jar"]
