# =========================
# Build stage
# =========================
FROM maven:3.9.11-eclipse-temurin-21 AS build

WORKDIR /app

# Copy the root parent POM
COPY pom.xml .

# Copy required modules
COPY common ./common
COPY patient-service/patient-service ./patient-service/patient-service

# Install only the parent POM
# -N means do not build the modules listed in the parent POM
RUN mvn -N install -DskipTests

# Build and install common module
RUN mvn -f common/pom.xml clean install -DskipTests

# Build patient-service
RUN mvn -f patient-service/patient-service/pom.xml clean package -DskipTests


# =========================
# Runtime stage
# =========================
FROM eclipse-temurin:21-jre

WORKDIR /app

# Copy generated patient-service JAR
COPY --from=build /app/patient-service/patient-service/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]