server:
  port: ${PORT:8086}

spring:
  application:
    name: storage-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:medsync-super-secret-key-change-in-production-min-32-chars}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

aws:
  region: ${AWS_REGION:ap-south-2}
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket: ${AWS_S3_BUCKET:medsync-discharge-summaries}