spring.application.name=notification-service
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

sendgrid.api-key=${SENDGRID_API_KEY:}
sendgrid.from-email=${SENDGRID_FROM_EMAIL:no-reply@medsync.com}
sendgrid.from-name=MedSync Hospital

jwt.secret=${JWT_SECRET:medsync-super-secret-key-change-in-production-min-32-chars}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html